/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_mark_myapplication_myNDK */

#ifndef _Included_com_example_mark_myapplication_myNDK
#define _Included_com_example_mark_myapplication_myNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_mark_myapplication_myNDK
 * Method:    getMystring
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_mark_myapplication_myNDK_getMystring
  (JNIEnv *, jobject);

/*
 * Class:     com_example_mark_myapplication_myNDK
 * Method:    gray
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_mark_myapplication_myNDK_gray
  (JNIEnv *, jobject, jintArray, jint, jint);

/*
 * Class:     com_example_mark_myapplication_myNDK
 * Method:    geCount
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_example_mark_myapplication_myNDK_geCount
  (JNIEnv *, jobject);

/*
 * Class:     com_example_mark_myapplication_myNDK
 * Method:    setone
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_mark_myapplication_myNDK_setone
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
